# Generated by Django 3.1.7 on 2021-04-24 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='id_artist',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='id_playlist',
        ),
        migrations.RemoveField(
            model_name='song',
            name='id_song',
        ),
        migrations.RemoveField(
            model_name='type',
            name='id_type',
        ),
    ]
