# Generated by Django 3.2 on 2021-04-30 14:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial_backup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist_Songs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.DeleteModel(
            name='Type',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='id_artist',
        ),
        migrations.AddField(
            model_name='artist',
            name='image_artist',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='customuser',
            name='cache',
            field=models.JSONField(default={'data': ''}),
        ),
        migrations.AddField(
            model_name='customuser',
            name='image_user',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='playlist',
            name='image_playlist',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='playlist',
            name='user_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='song',
            name='aritst',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.artist'),
        ),
        migrations.AddField(
            model_name='song',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='song',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='song',
            name='listen_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='song',
            name='name_type',
            field=models.CharField(blank=True, choices=[('Vpop', 'Vpop'), ('Kpop', 'Kpop'), ('USUK', 'USUK')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='upload_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='playlist',
            unique_together={('user_name', 'name_playlist')},
        ),
        migrations.AlterUniqueTogether(
            name='song',
            unique_together={('name_song', 'upload_by')},
        ),
        migrations.AddField(
            model_name='playlist_songs',
            name='playlist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.playlist'),
        ),
        migrations.AddField(
            model_name='playlist_songs',
            name='song',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.song'),
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='id_playlist',
        ),
        migrations.RemoveField(
            model_name='song',
            name='id_song',
        ),
        migrations.AlterUniqueTogether(
            name='playlist_songs',
            unique_together={('song', 'playlist')},
        ),
    ]
