# Generated by Django 3.1.7 on 2021-04-24 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210424_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='image_artist',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='customuser',
            name='image_user',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='playlist',
            name='image_playlist',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
