# Generated by Django 3.1.7 on 2021-04-25 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210424_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='aritst',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.artist'),
        ),
    ]
