# Generated by Django 3.1.7 on 2021-04-25 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_song_aritst'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='name_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.type'),
        ),
    ]
