# Generated by Django 3.2 on 2021-05-09 17:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_cache'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality', models.CharField(blank=True, choices=[('1 star', '1 Star'), ('2 stars', '2 Stars'), ('3 stars', '3 Stars'), ('4 stars', '4 Stars'), ('5 stars', '5 Stars')], max_length=20, null=True)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.song')),
                ('user_rated', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user_rated', 'song')},
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.song')),
                ('uploaded_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('uploaded_user', 'song')},
            },
        ),
    ]
