# Generated by Django 3.2 on 2021-05-21 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_comments_rating'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='comments',
            unique_together=set(),
        ),
    ]
