# Generated by Django 3.1.7 on 2021-04-25 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_song_name_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='name_song',
            field=models.ManyToManyField(to='users.Song'),
        ),
    ]
