# Generated by Django 3.2 on 2021-05-30 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_comments_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='info_artist',
            field=models.CharField(max_length=500, null=True, verbose_name='Infomation'),
        ),
    ]
