# Generated by Django 3.1.7 on 2021-04-25 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_playlist_name_song'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='name_song',
        ),
        migrations.AddField(
            model_name='song',
            name='playlist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.playlist'),
        ),
    ]
