# Generated by Django 3.2 on 2021-06-07 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_artist_info_artist'),
        ('users', '0007_auto_20210522_2215'),
    ]

    operations = [
    ]
