# Generated by Django 3.1.7 on 2021-04-26 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_song_audio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='name_type',
            field=models.CharField(blank=True, choices=[('Vpop', 'Vpop'), ('Kpop', 'Kpop'), ('USUK', 'USUK')], max_length=20, null=True),
        ),
    ]
