# Generated by Django 3.1.7 on 2021-04-26 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20210426_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='name_playlist',
            field=models.CharField(max_length=30, null=True, unique=True, verbose_name='Name Playlist'),
        ),
    ]
