# Generated by Django 3.1.7 on 2021-04-29 06:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20210427_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='cache',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
