# Generated by Django 3.2 on 2021-04-29 12:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20210429_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='listen_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='song',
            name='upload_by',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='song',
            unique_together={('name_song', 'upload_by')},
        ),
    ]
