# Generated by Django 3.2 on 2021-04-29 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_alter_song_upload_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist_Songs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.playlist')),
                ('song', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.song')),
            ],
            options={
                'unique_together': {('song', 'playlist')},
            },
        ),
    ]
